-- ============================================
-- Script de inicialización de base de datos
-- ENCOMIEXPRESS
-- ============================================

-- Crear base de datos (ejecutar primero)
-- CREATE DATABASE encomiexpress;

-- ============================================
-- TABLAS
-- ============================================

CREATE TABLE "rol" (
  "idRol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "descripcion" varchar(200),
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "permiso" (
  "idPermiso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "descripcion" varchar(200),
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rolPermiso" (
  "idRolPermiso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idRol" integer NOT NULL,
  "idPermiso" integer NOT NULL
);

CREATE TABLE "usuario" (
  "idUsuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idRol" integer NOT NULL,
  "tipoIdentificacion" varchar(20) NOT NULL,
  "numeroIdentificacion" varchar(20) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "email" varchar(150) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "conductor" (
  "idConductor" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idUsuario" integer UNIQUE NOT NULL,
  "categoriaLicencia" varchar(10),
  "numeroLicencia" varchar(20),
  "vencimientoLicencia" date,
  "estado" varchar(30) NOT NULL DEFAULT 'activo',
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipoIdentificacion" varchar(20) NOT NULL,
  "numeroIdentificacion" varchar(20) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "email" varchar(150),
  "direccion" varchar(255),
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "propietarioVehiculo" (
  "idPropietario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipoIdentificacion" varchar(20) NOT NULL,
  "numeroIdentificacion" varchar(20) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "email" varchar(150),
  "tarjetaPropiedad" varchar(50),
  "tipoFlota" varchar(50),
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "vehiculo" (
  "idVehiculo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idConductor" integer NOT NULL,
  "idPropietario" integer NOT NULL,
  "placa" varchar(10) UNIQUE NOT NULL,
  "marca" varchar(50),
  "modelo" varchar(50),
  "color" varchar(30),
  "tipo" varchar(50),
  "capacidad" decimal(10,2),
  "estado" varchar(30) NOT NULL DEFAULT 'disponible',
  "habilitado" boolean NOT NULL DEFAULT true,
  "fechaRegistro" date,
  "vencimientoSOAT" date,
  "vencimientoRevisionTecnica" date,
  "vencimientoSeguroTerceros" date
);

CREATE TABLE "destino" (
  "idDestino" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departamento" varchar(60) NOT NULL,
  "ciudad" varchar(60) NOT NULL,
  "tarifaBase" decimal(12,2) NOT NULL DEFAULT 0,
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "ruta" (
  "idRuta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idVehiculo" integer NOT NULL,
  "idConductor" integer NOT NULL,
  "idDestino" integer NOT NULL,
  "horaSalida" time,
  "horaLlegadaEstimada" time,
  "habilitado" boolean NOT NULL DEFAULT true,
  "fechaCreacion" date NOT NULL DEFAULT (CURRENT_DATE)
);

CREATE TABLE "anticipoExcedente" (
  "idAnticipoExcedente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idConductor" integer NOT NULL,
  "idRuta" integer NOT NULL,
  "valorAnticipo" decimal(12,2) NOT NULL DEFAULT 0,
  "valorGastado" decimal(12,2) DEFAULT 0,
  "excedente" decimal(12,2) DEFAULT 0,
  "estado" varchar(30) NOT NULL DEFAULT 'pendiente',
  "soporte" varchar(500),
  "fechaEntrega" date,
  "fechaLegalizacion" date,
  "fechaEntregaExcedente" date
);

CREATE TABLE "encomiendaVenta" (
  "idEncomiendaVenta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idCliente" integer NOT NULL,
  "idRuta" integer NOT NULL,
  "numeroGuia" varchar(50) UNIQUE NOT NULL,
  "numeroFactura" varchar(50),
  "fechaRegistro" date NOT NULL DEFAULT (CURRENT_DATE),
  "fechaHoraEmision" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "fechaEstimadaEntrega" date,
  "estado" varchar(30) NOT NULL DEFAULT 'pendiente de recogida',
  "observaciones" text,
  "valorServicio" decimal(12,2) NOT NULL DEFAULT 0,
  "impuestos" decimal(12,2) DEFAULT 0,
  "total" decimal(12,2) NOT NULL DEFAULT 0,
  "metodoPago" varchar(30),
  "estadoPago" varchar(20) NOT NULL DEFAULT 'pendiente',
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "destinatario" (
  "idDestinatario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idEncomiendaVenta" integer NOT NULL,
  "nombreDestinatario" varchar(150) NOT NULL,
  "telefonoDestinatario" varchar(20),
  "direccionDestinatario" varchar(255)
);

CREATE TABLE "paquete" (
  "idPaquete" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idEncomiendaVenta" integer NOT NULL,
  "descripcionContenido" text,
  "peso" decimal(8,2),
  "alto" decimal(8,2),
  "ancho" decimal(8,2),
  "profundidad" decimal(8,2),
  "valorDeclarado" decimal(12,2)
);

-- ============================================
-- ÍNDICES
-- ============================================

CREATE UNIQUE INDEX "rolPermiso_unique" ON "rolPermiso" ("idRol", "idPermiso");

-- ============================================
-- COMENTARIOS
-- ============================================

COMMENT ON COLUMN "permiso"."nombre" IS 'ej: clientes, encomiendas, vehiculos';
COMMENT ON COLUMN "usuario"."password" IS 'hash bcrypt';
COMMENT ON COLUMN "vehiculo"."placa" IS 'Colombia: 6 chars';
COMMENT ON COLUMN "anticipoExcedente"."soporte" IS 'URL Cloudinary';
COMMENT ON COLUMN "encomiendaVenta"."estado" IS 'pendiente de recogida | en recogida | programada | en tránsito | entregado | devuelto';

-- ============================================
-- LLAVES FORÁNEAS
-- ============================================

ALTER TABLE "rolPermiso" ADD FOREIGN KEY ("idRol") REFERENCES "rol" ("idRol") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "rolPermiso" ADD FOREIGN KEY ("idPermiso") REFERENCES "permiso" ("idPermiso") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "usuario" ADD FOREIGN KEY ("idRol") REFERENCES "rol" ("idRol") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "vehiculo" ADD FOREIGN KEY ("idConductor") REFERENCES "conductor" ("idConductor") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "vehiculo" ADD FOREIGN KEY ("idPropietario") REFERENCES "propietarioVehiculo" ("idPropietario") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ruta" ADD FOREIGN KEY ("idVehiculo") REFERENCES "vehiculo" ("idVehiculo") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ruta" ADD FOREIGN KEY ("idConductor") REFERENCES "conductor" ("idConductor") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "ruta" ADD FOREIGN KEY ("idDestino") REFERENCES "destino" ("idDestino") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "anticipoExcedente" ADD FOREIGN KEY ("idConductor") REFERENCES "conductor" ("idConductor") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "anticipoExcedente" ADD FOREIGN KEY ("idRuta") REFERENCES "ruta" ("idRuta") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "encomiendaVenta" ADD FOREIGN KEY ("idCliente") REFERENCES "cliente" ("id") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "encomiendaVenta" ADD FOREIGN KEY ("idRuta") REFERENCES "ruta" ("idRuta") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "destinatario" ADD FOREIGN KEY ("idEncomiendaVenta") REFERENCES "encomiendaVenta" ("idEncomiendaVenta") DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE "paquete" ADD FOREIGN KEY ("idEncomiendaVenta") REFERENCES "encomiendaVenta" ("idEncomiendaVenta") DEFERRABLE INITIALLY IMMEDIATE;

-- ============================================
-- DATOS INICIALES
-- ============================================

-- Roles
INSERT INTO "rol" ("nombre", "descripcion") VALUES 
('admin', 'Administrador del sistema con acceso total'),
('usuario', 'Usuario que puede registrar encomiendas'),
('conductor', 'Conductor de vehículo');

-- Permisos
INSERT INTO "permiso" ("nombre", "descripcion") VALUES 
('usuarios', 'Gestión de usuarios'),
('roles', 'Gestión de roles y permisos'),
('clientes', 'Gestión de clientes'),
('conductores', 'Gestión de conductores'),
('vehiculos', 'Gestión de vehículos'),
('destinos', 'Gestión de destinos'),
('rutas', 'Gestión de rutas'),
('encomiendas', 'Gestión de encomiendas'),
('anticipos', 'Gestión de anticipos');

-- Asignar permisos a roles
-- Admin tiene todos los permisos
INSERT INTO "rolPermiso" ("idRol", "idPermiso") 
SELECT 1, "idPermiso" FROM "permiso";

-- Usuario tiene permisos limitados
INSERT INTO "rolPermiso" ("idRol", "idPermiso") VALUES 
(2, 3), -- clientes
(2, 8); -- encomiendas

-- Conductor tiene permisos de conductor y encomiendas
INSERT INTO "rolPermiso" ("idRol", "idPermiso") VALUES 
(3, 4), -- conductores
(3, 5), -- vehiculos
(3, 6), -- destinos
(3, 7), -- rutas
(3, 8), -- encomiendas
(3, 9); -- anticipos

-- Usuario admin inicial (password: admin123)
INSERT INTO "usuario" ("idRol", "tipoIdentificacion", "numeroIdentificacion", "nombre", "apellido", "telefono", "email", "password") VALUES 
(1, 'CC', '12345678', 'Administrador', 'Sistema', '3000000000', 'admin@encomiexpress.com', '$2a$10$rQEY5WqLQzGvYqU5VxXjXeQxJxJxJxJxJxJxJxJxJxJxJxJxJ');

-- Destinos de ejemplo
INSERT INTO "destino" ("departamento", "ciudad", "tarifaBase") VALUES 
('Antioquia', 'Medellín', 25000),
('Cundinamarca', 'Bogotá', 20000),
('Valle del Cauca', 'Cali', 30000),
('Atlántico', 'Barranquilla', 35000),
('Santander', 'Bucaramanga', 28000);
