-- ============================================
-- Script de inicialización de base de datos
-- ENCOMIEXPRESS
-- ============================================

-- Crear base de datos (ejecutar primero)
-- CREATE DATABASE encomiexpress;

-- ============================================
-- TABLAS
-- ============================================

CREATE TABLE "rol" (
  "idRol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "descripcion" varchar(200),
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "permiso" (
  "idPermiso" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) NOT NULL,
  "descripcion" varchar(200),
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rolPermiso" (
  "idRol" integer NOT NULL,
  "idPermiso" integer NOT NULL,
  PRIMARY KEY ("idRol", "idPermiso")
);

CREATE TABLE "usuario" (
  "idUsuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idRol" integer NOT NULL,
  "tipoIdentificacion" varchar(20) NOT NULL,
  "numeroIdentificacion" varchar(20) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "email" varchar(150) UNIQUE NOT NULL,
  "password" varchar(255) NOT NULL,
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "conductor" (
  "idConductor" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idUsuario" integer UNIQUE NOT NULL,
  "categoriaLicencia" varchar(10),
  "numeroLicencia" varchar(20),
  "vencimientoLicencia" date,
  "estado" varchar(30) NOT NULL DEFAULT 'activo',
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "cliente" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipoIdentificacion" varchar(20) NOT NULL,
  "numeroIdentificacion" varchar(20) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "email" varchar(150),
  "direccion" varchar(255),
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "propietarioVehiculo" (
  "idPropietario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tipoIdentificacion" varchar(20) NOT NULL,
  "numeroIdentificacion" varchar(20) UNIQUE NOT NULL,
  "nombre" varchar(100) NOT NULL,
  "apellido" varchar(100) NOT NULL,
  "telefono" varchar(20),
  "email" varchar(150),
  "tarjetaPropiedad" varchar(50),
  "tipoFlota" varchar(50),
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "vehiculo" (
  "idVehiculo" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idConductor" integer NOT NULL,
  "idPropietario" integer NOT NULL,
  "placa" varchar(10) UNIQUE NOT NULL,
  "marca" varchar(50),
  "modelo" varchar(50),
  "color" varchar(30),
  "tipo" varchar(50),
  "capacidad" decimal(10,2),
  "estado" varchar(30) NOT NULL DEFAULT 'disponible',
  "habilitado" boolean NOT NULL DEFAULT true,
  "fechaRegistro" date,
  "vencimientoSOAT" date,
  "vencimientoRevisionTecnica" date,
  "vencimientoSeguroTerceros" date
);

CREATE TABLE "destino" (
  "idDestino" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "departamento" varchar(60) NOT NULL,
  "ciudad" varchar(60) NOT NULL,
  "tarifaBase" decimal(12,2) NOT NULL DEFAULT 0,
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "ruta" (
  "idRuta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idVehiculo" integer NOT NULL,
  "idConductor" integer NOT NULL,
  "idDestino" integer NOT NULL,
  "horaSalida" time,
  "horaLlegadaEstimada" time,
  "habilitado" boolean NOT NULL DEFAULT true,
  "fechaCreacion" date NOT NULL DEFAULT (CURRENT_DATE)
);

CREATE TABLE "anticipoExcedente" (
  "idAnticipoExcedente" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idConductor" integer NOT NULL,
  "idRuta" integer NOT NULL,
  "valorAnticipo" decimal(12,2) NOT NULL DEFAULT 0,
  "valorGastado" decimal(12,2) DEFAULT 0,
  "excedente" decimal(12,2) DEFAULT 0,
  "estado" varchar(30) NOT NULL DEFAULT 'pendiente',
  "soporte" varchar(500),
  "fechaEntrega" date,
  "fechaLegalizacion" date,
  "fechaEntregaExcedente" date
);

CREATE TABLE "encomiendaVenta" (
  "idEncomiendaVenta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idCliente" integer NOT NULL,
  "idRuta" integer NOT NULL,
  "numeroGuia" varchar(50) UNIQUE NOT NULL,
  "numeroFactura" varchar(50),
  "fechaRegistro" date NOT NULL DEFAULT (CURRENT_DATE),
  "fechaHoraEmision" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "fechaEstimadaEntrega" date,
  "estado" varchar(30) NOT NULL DEFAULT 'pendiente de recogida',
  "observaciones" text,
  "valorServicio" decimal(12,2) NOT NULL DEFAULT 0,
  "impuestos" decimal(12,2) DEFAULT 0,
  "total" decimal(12,2) NOT NULL DEFAULT 0,
  "metodoPago" varchar(30),
  "estadoPago" varchar(20) NOT NULL DEFAULT 'pendiente',
  "habilitado" boolean NOT NULL DEFAULT true
);

CREATE TABLE "destinatario" (
  "idDestinatario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idEncomiendaVenta" integer NOT NULL,
  "nombreDestinatario" varchar(150) NOT NULL,
  "telefonoDestinatario" varchar(20),
  "direccionDestinatario" varchar(255)
);

CREATE TABLE "paquete" (
  "idPaquete" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "idEncomiendaVenta" integer NOT NULL,
  "descripcionContenido" text,
  "peso" decimal(8,2),
  "alto" decimal(8,2),
  "ancho" decimal(8,2),
  "profundidad" decimal(8,2),
  "valorDeclarado" decimal(12,2)
);

-- ============================================
-- COMENTARIOS
-- ============================================

COMMENT ON COLUMN "permiso"."nombre" IS 'ej: clientes, encomiendas, vehiculos';
COMMENT ON COLUMN "usuario"."password" IS 'hash bcrypt';
COMMENT ON COLUMN "vehiculo"."placa" IS 'Colombia: 6 chars';
COMMENT ON COLUMN "anticipoExcedente"."soporte" IS 'URL Cloudinary';
COMMENT ON COLUMN "encomiendaVenta"."estado" IS 'pendiente de recogida | en recogida | programada | en tránsito | entregado | devuelto';

-- ============================================
-- LLAVES FORÁNEAS
-- ============================================

ALTER TABLE "rolPermiso" ADD FOREIGN KEY ("idRol") REFERENCES "rol" ("idRol");
ALTER TABLE "rolPermiso" ADD FOREIGN KEY ("idPermiso") REFERENCES "permiso" ("idPermiso");
ALTER TABLE "usuario" ADD FOREIGN KEY ("idRol") REFERENCES "rol" ("idRol");
ALTER TABLE "conductor" ADD FOREIGN KEY ("idUsuario") REFERENCES "usuario" ("idUsuario");
ALTER TABLE "vehiculo" ADD FOREIGN KEY ("idConductor") REFERENCES "conductor" ("idConductor");
ALTER TABLE "vehiculo" ADD FOREIGN KEY ("idPropietario") REFERENCES "propietarioVehiculo" ("idPropietario");
ALTER TABLE "ruta" ADD FOREIGN KEY ("idVehiculo") REFERENCES "vehiculo" ("idVehiculo");
ALTER TABLE "ruta" ADD FOREIGN KEY ("idConductor") REFERENCES "conductor" ("idConductor");
ALTER TABLE "ruta" ADD FOREIGN KEY ("idDestino") REFERENCES "destino" ("idDestino");
ALTER TABLE "anticipoExcedente" ADD FOREIGN KEY ("idConductor") REFERENCES "conductor" ("idConductor");
ALTER TABLE "anticipoExcedente" ADD FOREIGN KEY ("idRuta") REFERENCES "ruta" ("idRuta");
ALTER TABLE "encomiendaVenta" ADD FOREIGN KEY ("idCliente") REFERENCES "cliente" ("id");
ALTER TABLE "encomiendaVenta" ADD FOREIGN KEY ("idRuta") REFERENCES "ruta" ("idRuta");
ALTER TABLE "destinatario" ADD FOREIGN KEY ("idEncomiendaVenta") REFERENCES "encomiendaVenta" ("idEncomiendaVenta");
ALTER TABLE "paquete" ADD FOREIGN KEY ("idEncomiendaVenta") REFERENCES "encomiendaVenta" ("idEncomiendaVenta");

-- ============================================
-- DATOS INICIALES
-- ============================================

-- Roles
INSERT INTO "rol" ("nombre", "descripcion") VALUES 
('admin', 'Administrador del sistema con acceso total'),
('usuario', 'Usuario que puede registrar encomiendas'),
('conductor', 'Conductor de vehículo');

-- Permisos
INSERT INTO "permiso" ("nombre", "descripcion", "habilitado") VALUES
('listar_usuario', 'Listar usuarios', true),
('registrar_usuario', 'Registrar usuarios', true),
('consultar_usuario', 'Consultar usuarios', true),
('actualizar_usuario', 'Actualizar usuarios', true),
('inhabilitar_usuario', 'Inhabilitar usuarios', true),
('listar_rol', 'Listar roles', true),
('registrar_rol', 'Registrar roles', true),
('consultar_rol', 'Consultar roles', true),
('actualizar_rol', 'Actualizar roles', true),
('listar_cliente', 'Listar clientes', true),
('registrar_cliente', 'Registrar clientes', true),
('consultar_cliente', 'Consultar clientes', true),
('actualizar_cliente', 'Actualizar clientes', true),
('inhabilitar_cliente', 'Inhabilitar clientes', true),
('listar_vehiculo', 'Listar vehículos', true),
('registrar_vehiculo', 'Registrar vehículos', true),
('consultar_vehiculo', 'Consultar vehículos', true),
('actualizar_vehiculo', 'Actualizar vehículos', true),
('listar_conductor', 'Listar conductores', true),
('registrar_conductor', 'Registrar conductores', true),
('consultar_conductor', 'Consultar conductores', true),
('actualizar_conductor', 'Actualizar conductores', true),
('listar_destino', 'Listar destinos', true),
('registrar_destino', 'Registrar destinos', true),
('consultar_destino', 'Consultar destinos', true),
('actualizar_destino', 'Actualizar destinos', true),
('listar_ruta', 'Listar rutas', true),
('registrar_ruta', 'Registrar rutas', true),
('consultar_ruta', 'Consultar rutas', true),
('actualizar_ruta', 'Actualizar rutas', true),
('listar_ruta_programacion', 'Listar rutas programación', true),
('registrar_ruta_programacion', 'Registrar rutas programación', true),
('consultar_ruta_programacion', 'Consultar rutas programación', true),
('actualizar_ruta_programacion', 'Actualizar rutas programación', true),
('listar_anticipo', 'Listar anticipos', true),
('registrar_anticipo', 'Registrar anticipos', true),
('consultar_anticipo', 'Consultar anticipos', true),
('actualizar_anticipo', 'Actualizar anticipos', true),
('listar_encomienda', 'Listar encomiendas', true),
('registrar_encomienda', 'Registrar encomiendas', true),
('consultar_encomienda', 'Consultar encomiendas', true),
('actualizar_encomienda', 'Actualizar encomiendas', true),
('gestion_transporte', 'Gestión de transporte', true),
('ver_dashboard', 'Ver dashboard', true);

-- Asignar todos los permisos al admin
INSERT INTO "rolPermiso" ("idRol", "idPermiso")
SELECT 1, "idPermiso" FROM "permiso" WHERE "habilitado" = true;

-- Usuario admin inicial (password: admin123)
INSERT INTO "usuario" ("idRol", "tipoIdentificacion", "numeroIdentificacion", "nombre", "apellido", "telefono", "email", "password") VALUES 
(1, 'CC', '12345678', 'Administrador', 'Sistema', '3000000000', 'admin@encomiexpress.com', '$2a$10$T/qc0d/DChPQw8BSiuRljesqJLSk89uKCx9TMaoGJqho.LCkNpVJW');

-- Destinos de ejemplo
INSERT INTO "destino" ("departamento", "ciudad", "tarifaBase") VALUES 
('Antioquia', 'Medellín', 25000),
('Cundinamarca', 'Bogotá', 20000),
('Valle del Cauca', 'Cali', 30000),
('Atlántico', 'Barranquilla', 35000),
('Santander', 'Bucaramanga', 28000);